[env]
TERM = "xterm-256color"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.8
startup_mode = "Maximized"

[terminal]

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]
